using InfluxDB.Client.Core;

namespace LeakTestService.Models;

/// <summary>
/// Represents a LeakTest.
/// </summary>

[Measurement("LeakTest")]
public class LeakTest
{
    [Column(IsTimestamp = true)] public DateTime TimeStamp { get; set; }

    // tags 
    [Column("TestObjectId", IsTag = true)] public Guid TestObjectId { get; set; }
    [Column("Status", IsTag = true)] public string Status { get; set; }
    [Column("MachineId", IsTag = true)] public Guid MachineId { get; set;  }
    [Column("TestObjectType", IsTag = true)] public string TestObjectType { get; set; }
    [Column("User", IsTag = true)] public string User { get; set; }

    // fields
    [Column("SniffingPoint")] public string SniffingPoint { get; set; }
    [Column("Reason")] public string? Reason { get; set; }
    
    /// <summary>
    /// Gets or sets the unique identifier for the leak test.
    /// This field should not be passed from the client, but is generated by the API.
    /// </summary>
    [Column("LeakTestId")] public Guid? LeakTestId { get; set; }

    public string? Measurement { get; set; }

    public Dictionary<string, string>? Links { get; set; }
    
}